// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFBackEnd.Api.Data;

namespace TFBackEnd.Api.Migrations
{
    [DbContext(typeof(TFBackEndApiContext))]
    partial class TFBackEndApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("SensorTelefono", b =>
                {
                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("TelefonosId")
                        .HasColumnType("int");

                    b.HasKey("SensorId", "TelefonosId");

                    b.HasIndex("TelefonosId");

                    b.ToTable("SensorTelefono");
                });

            modelBuilder.Entity("TFBackEnd.Models.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("InstalacionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstalacionId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("TFBackEnd.Models.Instalacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Exitosa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Instalaciones");
                });

            modelBuilder.Entity("TFBackEnd.Models.Operario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<int?>("InstalacionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstalacionId");

                    b.ToTable("Operarios");
                });

            modelBuilder.Entity("TFBackEnd.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("TFBackEnd.Models.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("InstalacionId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<float>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("InstalacionId");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("SensorTelefono", b =>
                {
                    b.HasOne("TFBackEnd.Models.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFBackEnd.Models.Telefono", null)
                        .WithMany()
                        .HasForeignKey("TelefonosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TFBackEnd.Models.App", b =>
                {
                    b.HasOne("TFBackEnd.Models.Instalacion", "Instalacion")
                        .WithMany("Apps")
                        .HasForeignKey("InstalacionId");

                    b.Navigation("Instalacion");
                });

            modelBuilder.Entity("TFBackEnd.Models.Operario", b =>
                {
                    b.HasOne("TFBackEnd.Models.Instalacion", "Instalacion")
                        .WithMany("Operarios")
                        .HasForeignKey("InstalacionId");

                    b.Navigation("Instalacion");
                });

            modelBuilder.Entity("TFBackEnd.Models.Telefono", b =>
                {
                    b.HasOne("TFBackEnd.Models.Instalacion", "Instalacion")
                        .WithMany("Telefonos")
                        .HasForeignKey("InstalacionId");

                    b.Navigation("Instalacion");
                });

            modelBuilder.Entity("TFBackEnd.Models.Instalacion", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("Operarios");

                    b.Navigation("Telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
